/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6236a5fc-fee0-4050-8c14-088d4743b49f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_I1prIpVZS",
    "aws_user_pools_web_client_id": "3abec47inidl6fqaqov8p5lr2d",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wibpbq3qtbcp7jjczwsbxj7i5y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
